name:                keli-compiler
version:             0.1.0.0
github:              "githubuser/keli-compiler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/keli-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- text
- parsec
- unordered-containers
- ordered-containers
- containers
- hspec
- pretty-simple
- process
- directory
- strings
- MissingH

library:
  source-dirs: src

executables:
  keli-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - keli-compiler

tests:
  keli-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - keli-compiler
    - hspec
